version: "2"
services:
  mongodb:
    image: mongo
    hostname: mongodb
    container_name: mongodb
    expose:
      - "27017"
    ports:
      - "27018:27017"
    volumes:
      - mongodb-volume:/data

  orion:
    image: fiware/orion:1.7.0
    hostname: orion
    container_name: orion
    links:
      - mongodb
    expose:
      - "1026"
    ports:
      - "1026:1026"
    command: -dbhost mongodb


volumes:
  mongodb-volume:
